export const ApiErrorCode = {
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_RATE_LIMITED: 'AUTH_RATE_LIMITED',
  AUTH_USERNAME_REQUIRED: 'AUTH_USERNAME_REQUIRED',
  AUTH_PASSWORD_REQUIRED: 'AUTH_PASSWORD_REQUIRED',
  AUTH_FIELDS_REQUIRED: 'AUTH_FIELDS_REQUIRED',
  AUTH_ACCESS_DENIED: 'AUTH_ACCESS_DENIED',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  EXCEL_IMPORT_ERROR: 'EXCEL_IMPORT_ERROR',
  EXCEL_EXPORT_EMPTY: 'EXCEL_EXPORT_EMPTY',
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
} as const;

export type ApiErrorCodeType = (typeof ApiErrorCode)[keyof typeof ApiErrorCode];
